mm/page_alloc : `Clean unused variable`
../mm/page_alloc.c:887:7: error: implicit declaration of function 'compaction_capture' [-Werror,-Wimplicit-function-declaration]
                if (compaction_capture(capc, page, order, migratetype)) {
                    ^
../mm/page_alloc.c:887:26: error: use of undeclared identifier 'capc'
                if (compaction_capture(capc, page, order, migratetype)) {