include: soc/qcom: pm: Fix failed inline call
Fixes the following compilation error (by GCC):

In file included from ../techpack/audio/asoc/codecs/sdm660_cdc/sdm660-cdc-irq.c:20:
../include/soc/qcom/pm.h: In function 'wcd9xxx_spmi_lock_sleep':
../include/soc/qcom/pm.h:24:12: error: inlining failed in call to 'always_inline' 'msm_cpuidle_get_deep_idle_latency': function body not available
   24 | inline s32 msm_cpuidle_get_deep_idle_latency(void);
      |            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../techpack/audio/asoc/codecs/sdm660_cdc/sdm660-cdc-irq.c:320:17: note: called from here
  320 |                 pm_qos_update_request(&map.pm_qos_req,
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  321 |                                       msm_cpuidle_get_deep_idle_latency());
      |                                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Fixes: 80cb3b0b36d ("lpm-levels: Allow CPU to idle when executing audio code")
Signed-off-by: Tashfin Shakeer Rhythm <tashfinshakeerrhythm@gmail.com>